### ISSUE TITLE
elm: Map.!: given key is not an element in the map

### ISSUE THREAD

**Issue by glasserc** [Gizra/elm-debouncer#13]
Hi! I started using `elm-debouncer` and from what I can see it looks great. However, when I try to build using `elm-make --debug` I get the error message in the title. I think it's because of the issue in https://github.com/elm/compiler/issues/1864 (and related issues). In particular, I think it's because the `Debouncer.Basic.Msg` type uses types from `Debouncer.Msg.Internal`, which isn't exposed. I can reproduce this using the example code in `Debouncer.Basic` -- I just copied it into a new project and tried building it using `elm make --debug src/Main.elm`.

To work around this, I forked the package to https://github.com/glasserc/elm-debouncer and exposed the internal module and slapped some text in there to fool the compiler into thinking I'd documented it. I know this isn't by any means ideal because `Debouncer.Internal` is meant to be internal... but do you think it would be worth exposing the module here too as long as the Elm compiler has this bug? If not, don't worry about it, I can continue using my fork when I'm debugging.

**Comment by mcmire** [comment]
I just received this error and upgrading to Elm 0.19.1 seemed to fix the issue.

**Comment by glasserc** [comment]
Yes, I've also heard that this issue was fixed in 0.19.1. I've archived my fork. Thanks for the notification!
