### ISSUE TITLE
`throttle`, or `debounce` with `emitFirstInput`, don't work

### ISSUE THREAD

**Issue by AdrianoFerrari** [Gizra/elm-debouncer#8]
Thanks for the library @rgrempel , very well thought out API.

I'm using it in my word processor app, to throttle my "add to document history" action, especially when making many rapid changes (i.e. moving a card rapidly with the keyboard shouldn't save every intermediate step as a new "version").

**But** I can't seem to use `emitFirstInput` or its equivalent `emitWhenUnsettled (Just 0)`. Not sure if I'm doing something wrong, or if it's a bug.

In other words, **this works**:
```elm
defaultModel : Model
defaultModel =
    { debouncerState = Debouncer.debounce (3 * second) |> toDebouncer
    , workingTree = Trees.defaultModel
    -- other fields
    }
```

But these two **don't work**:
```elm
defaultModel : Model
defaultModel =
    { debouncerState =
         Debouncer.debounce (3 * second)
             |> Debouncer.emitFirstInput True
             |> toDebouncer
    , workingTree = Trees.defaultModel
    -- other fields
    }
```

```elm
defaultModel : Model
defaultModel =
    { debouncerState = Debouncer.throttle (3 * second) |> toDebouncer
    , workingTree = Trees.defaultModel
    -- other fields
    }
```

I've attached a video of this:
https://www.dropbox.com/s/18knk2xrxye8pwy/elm-debouncer-issue-2018-07-10_13.45.52.mkv?dl=0

And this the the code branch I'm working on:
https://github.com/gingko/client/tree/elm-debounce

**Comment by rgrempel** [comment]
Ah, that reminds me that I haven't actually written very good tests for this code. I'll write up a test to see if I can reproduce your report!

**Comment by rgrempel** [comment]
There seems to be a problem here:

https://github.com/gingko/client/blob/6ee017f46e88145d5f50c278c8fae824e383aaab/src/elm/Main.elm#L266-L269

I think the `model` should probably be `updatedModel` ... in the case where something is emitted, you're not actually keeping the new debouncer state. So, that would cause all sorts of unexpected behaviour.

**Comment by AdrianoFerrari** [comment]
Ok, I'll try changing that and let you know.

**Comment by AdrianoFerrari** [comment]
Yup, that was it.
```elm
    , debouncerState =
        Debouncer.throttle (3 * second)
            |> Debouncer.settleWhenQuietFor (Just <| 6 * second)
            |> toDebouncer
```

and `model` &rarr; `updatedModel` did the trick.

Thanks for your help :smile:

**Comment by rgrempel** [comment]
Very interesting app, by the way -- I'll have to give it a try sometime!

**Comment by AdrianoFerrari** [comment]
Thanks! :smile:
It feels different to write with it, but many have tried and liked it.
